name: build-zam
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Install glibc
        run: sudo apt-get update && sudo apt-get install -y libc6
      - name: Build jar
        run: mvn clean compile jib:build
      # Step 5: Install Railway CLI in the GitHub Actions runner
      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh
      # Step 6: Log in to Railway using API token
      - name: Railway Login
        run: railway login
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}


      # Step 4: Deploy directly from Docker Hub image
      - name: Deploy from Docker Hub
        run: railway up --image docker.io/${{ secrets.DOCKERHUB_USERNAME }}/theattorneyai:latest
#      - name: Deploy to test
#        uses: johnbeynon/render-deploy-action@v0.0.8
#        with:
#          service-id: srv-cvr6b2je5dus7387aij0
#          api-key: rnd_VmQJ50o6AWfdo2RB0vmrjOpur53F
#          wait-for-success: true

# https://api.render.com/deploy/srv-cvr6b2je5dus7387aij0?key=VciC2INsDjw
# https://api.render.com/deploy/srv-cvr6b2je5dus7387aij0?key=VciC2INsDjw
# https://api.render.com/deploy/srv-d28tmeer433s73bv9qbg?key=O_ecYtPkZc4